/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gasolineraventanas;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author anna
 */
public class VentanaInicial extends javax.swing.JFrame {

    /**
     * Creates new form VentanaInicial
     */
    public VentanaInicial() {
        initComponents();
        this.setLocationRelativeTo(null);
        ImageIcon img = new ImageIcon("src\\img\\icono.jpg");
        this.setIconImage(img.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBienvenidoV1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSegundosV1 = new javax.swing.JTextField();
        txtCantidadCochesV1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnComenzarV1 = new javax.swing.JButton();
        btnSalit = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gasolinera");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBienvenidoV1.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        lblBienvenidoV1.setText("BIENVENIDO A LA GASOLINERA DAM S.L");
        getContentPane().add(lblBienvenidoV1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 725, 62));

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel2.setText("Indique la cantidad de segundos que estará abierta la gasolinera");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 61));

        txtSegundosV1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        txtSegundosV1.setForeground(new java.awt.Color(0, 204, 0));
        getContentPane().add(txtSegundosV1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 90, 61));

        txtCantidadCochesV1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        txtCantidadCochesV1.setForeground(new java.awt.Color(0, 204, 0));
        getContentPane().add(txtCantidadCochesV1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, 90, 60));

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel3.setText("Indique la cantidad de vehiculos que irán a la gasolinera");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 480, 56));

        btnComenzarV1.setBackground(new java.awt.Color(0, 153, 153));
        btnComenzarV1.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        btnComenzarV1.setForeground(new java.awt.Color(51, 51, 51));
        btnComenzarV1.setText("COMENZAR");
        btnComenzarV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComenzarV1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnComenzarV1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 200, 60));

        btnSalit.setBackground(new java.awt.Color(0, 51, 204));
        btnSalit.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnSalit.setText("SALIR");
        btnSalit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalitActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalit, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 340, 80, 40));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/campo.jpg"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 780, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComenzarV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComenzarV1ActionPerformed
        // TODO add your handling code here:
        if (txtCantidadCochesV1.getText().equals("") || txtSegundosV1.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Tiene que introducir los dos datos", "Imposible comenzar :(", JOptionPane.OK_CANCEL_OPTION);
        } else {

            Monitor.setCantidadCoches(Integer.parseInt(txtCantidadCochesV1.getText()));
            Monitor.setTiempoJuego(Integer.parseInt(txtSegundosV1.getText()));
            new Monitor();
            new VentanaGasolinera().setVisible(true);
            this.dispose();
        }


    }//GEN-LAST:event_btnComenzarV1ActionPerformed

    private void btnSalitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalitActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Salimos del programa. Gracias por utilizar nuestra gasolinera");
        System.exit(0);
    }//GEN-LAST:event_btnSalitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComenzarV1;
    private javax.swing.JButton btnSalit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblBienvenidoV1;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JTextField txtCantidadCochesV1;
    private javax.swing.JTextField txtSegundosV1;
    // End of variables declaration//GEN-END:variables
}
