/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gasolineraventanas;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author anna
 */
public class VentanaGasolinera extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form VentanaGasolinera
     */
    Monitor mon = new Monitor(0);

    public VentanaGasolinera() {
        initComponents();
        this.setLocationRelativeTo(null);
        arrancarHiloArrancar();
        saberTipoCombustible();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCocheGasolina = new javax.swing.JTextField();
        txtCochesDiesel = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCantidadLitrosDiesel = new javax.swing.JTextField();
        txtInfoDiesel = new javax.swing.JTextField();
        txtInfoGasolina = new javax.swing.JTextField();
        txtCantidadLitrosGasolina = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTiempo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtGanador = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtGasolinero = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setForeground(java.awt.Color.white);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 48)); // NOI18N
        jLabel1.setText("GASOLINERA DAM S.L");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 550, 71));

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel2.setText("GRUPO GASOLINA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 140, 125, 20));

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel3.setText("GRUPO DIESEL");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 140, -1, 20));

        txtCocheGasolina.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        txtCocheGasolina.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(txtCocheGasolina, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 160, 100, 90));

        txtCochesDiesel.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        txtCochesDiesel.setForeground(new java.awt.Color(102, 102, 102));
        txtCochesDiesel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCochesDieselActionPerformed(evt);
            }
        });
        getContentPane().add(txtCochesDiesel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 160, 90, 90));

        jLabel4.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel4.setText("COCHE DIESEL");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 127, -1));

        jLabel5.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel5.setText("COCHE GASOLINA");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 300, 140, 40));

        jLabel6.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel6.setText("LITROS ACTUALES DE  GASOLINA");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 290, 230, 20));

        txtCantidadLitrosDiesel.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        txtCantidadLitrosDiesel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadLitrosDieselActionPerformed(evt);
            }
        });
        getContentPane().add(txtCantidadLitrosDiesel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 310, 93, 72));

        txtInfoDiesel.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        getContentPane().add(txtInfoDiesel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 570, 72));

        txtInfoGasolina.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        getContentPane().add(txtInfoGasolina, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 570, 72));

        txtCantidadLitrosGasolina.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        getContentPane().add(txtCantidadLitrosGasolina, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 310, 106, 71));

        jLabel7.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel7.setText("LITROS ACTUALES DE DIESEL");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 290, 210, 20));

        txtTiempo.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        txtTiempo.setForeground(new java.awt.Color(51, 255, 0));
        getContentPane().add(txtTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 530, 120, 74));

        jLabel8.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel8.setText("TIEMPO RESTANTE");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 490, 220, 40));

        txtGanador.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        txtGanador.setForeground(new java.awt.Color(255, 102, 0));
        getContentPane().add(txtGanador, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 531, 280, 80));

        jLabel9.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel9.setText("GRUPO GANADOR");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 500, 180, 26));

        txtGasolinero.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        getContentPane().add(txtGasolinero, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 313, 81));

        btnSalir.setBackground(new java.awt.Color(255, 255, 255));
        btnSalir.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 600, -1, 40));

        lblFondo.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carretera.jpg"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCochesDieselActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCochesDieselActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCochesDieselActionPerformed

    private void txtCantidadLitrosDieselActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadLitrosDieselActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadLitrosDieselActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Salimos del programa. Gracias por utilizar nuestra gasolinera");
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaGasolinera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaGasolinera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaGasolinera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaGasolinera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaGasolinera().setVisible(true);
            }
        });
    }

    public void saberTipoCombustible() {
        txtCochesDiesel.setText(" " + (Monitor.getContDiesel()));
        txtCocheGasolina.setText("" + (Monitor.getContGasolina()));
    }

    public void saberCantidadLitros() {
        txtCantidadLitrosDiesel.setText("" + Monitor.getDepositoDiesel() + " lts");
        txtCantidadLitrosGasolina.setText("" + Monitor.getDepositoGasolina() + " lts");
    }

    public void pintarTiempo() {
        txtTiempo.setText("" + Temporizador.getTiempo() + " seg");
    }

    public void pintarInfoLitros() {
        if (!Monitor.isControlLitros()) {
            txtInfoDiesel.setText("CANTIDAD DE LITROS: " + Monitor.getLitrosGrupoDiesel());
            txtInfoGasolina.setText("CANTIDAD DE LITROS: " + Monitor.getLitrosGrupoGasolina());
        } else {
            txtInfoDiesel.setText("EL DEPOSITO NO TENIA SUFICIENTES LITROS, LLEVA: " + Monitor.getLitrosGrupoDiesel());
            txtInfoGasolina.setText("EL DEPOSITO NO TENIA SUFICIENTES LITROS, LLEVA: " + Monitor.getLitrosGrupoGasolina());
        }

    }

    public void saberGanador() {
        txtGanador.setVisible(true);

        txtGanador.setText("" + Monitor.getNombreGanador());

    }

    public void pintarRepostar() {
        if (Monitor.isTurnoGasolinero()) {
            txtGasolinero.setText("REPOSTANDO");
        } else {
            txtGasolinero.setText("DEPOSITO REPOSTADO");
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JTextField txtCantidadLitrosDiesel;
    private javax.swing.JTextField txtCantidadLitrosGasolina;
    private javax.swing.JTextField txtCocheGasolina;
    private javax.swing.JTextField txtCochesDiesel;
    private javax.swing.JTextField txtGanador;
    private javax.swing.JTextField txtGasolinero;
    private javax.swing.JTextField txtInfoDiesel;
    private javax.swing.JTextField txtInfoGasolina;
    private javax.swing.JTextField txtTiempo;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        while (!mon.isFinPorGanador() || !mon.isFinTiempo()) {
            saberCantidadLitros();
            pintarTiempo();
            pintarRepostar();

            pintarInfoLitros();
            saberGanador();
            try {
                Thread.sleep(100);
            } catch (InterruptedException ex) {
                Logger.getLogger(VentanaGasolinera.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }

    public void arrancarHiloArrancar() {
        new Thread(this).start();
    }
}
